### ISSUE TITLE
Geração de boleto não concluída.

### ISSUE THREAD

**Issue by patric-vinicios** [akretion/boleto_cnab_api#27]
Seguindo os passos simples do Readme, pede-se para executar o cUrl na rota `localhost:9292/api/boleto/multi` porém os arquivos mencionados não são criados e a pasta tmp continua vazia.

Passos realizados:
```
docker build -t akretion/boleto_cnab_api .
docker run -ti -p 9292:9292 akretion/boleto_cnab_api
```
```
echo '[{"valor":5.0,"cedente":"Kivanio Barbosa","documento_cedente":"12345678912","sacado":"Claudio Pozzebom",
"sacado_documento":"12345678900","agencia":"0810","conta_corrente":"53678","convenio":12387,"nosso_numero":"12345678","bank":"itau"},
{"valor": 10.00,"cedente": "PREFEITURA MUNICIPAL DE VILHENA","documento_cedente": "04092706000181","sacado": "João Paulo Barbosa",
"sacado_documento": "77777777777","agencia": "1825","conta_corrente": "0000528","convenio": "245274","nosso_numero": "000000000000001","bank":"caixa"}]'\
> /tmp/boletos_data.json
curl -X POST -F type=pdf -F 'data=@/tmp/boletos_data.json' localhost:9292/api/boleto/multi > /tmp/boletos.pdf
```

Verificando arquivos na pasta /tmp/:
`ls -l /usr/src/app/tmp` => Resposta: 0

**Comment by mbcosta** [comment]
@patric-vinicios  você pode usar como referencia de implementação e uso do serviço o modulo feito em Python para o projeto de Localizar o Odoo para o Brasil https://github.com/OCA/l10n-brazil/tree/14.0/l10n_br_account_payment_brcobranca talvez ajude a entender melhor

* Emissão do Boleto https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_account_payment_brcobranca/models/account_move.py#L60 
* Geração do Arquivo de Envio CNAB aqui https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_account_payment_brcobranca/models/account_payment_order.py#L175 
* Processamento de um Arquivo de Retorno CNAB aqui https://github.com/OCA/l10n-brazil/blob/14.0/l10n_br_account_payment_brcobranca/parser/cnab_file_parser.py#L77

**Comment by patric-vinicios** [comment]
Consegui fazer ele gerar o .json, mas ainda tem alguns problemas.

1. Eu não consigo enviar o `-curl` caso esteja no `/bash` do contêiner.
2. Compartilhando um volume, ele gera o `.json` no meu local, mas exclui o arquivo `.pdf`
3. Quando eu derrubo o contêiner, ele exclui automaticamente todos os `.json` gerados

**Comment by mbcosta** [comment]
@patric-vinicios essa API foi pensada e estruturada com a ideia de ser um Micro-Serviço, é algo para ser uma camada entre uma Aplicação que precisa gerenciar Boletos/CNAB porém isolando a maior parte da lógica dentro dessa API, costuma ser usado dentro de um docker-compose que é uma forma de configurar mais de um Containers que são executados de forma separada porém se comunicam entre si, um exemplo disso é ter dentro de um docker-compose a Aplicação em um Container e o Banco de Dados em outro mas quando são iniciados pelo docker-compose esses dois containers trabalham em conjunto, isso é feito para pode separar ambientes/S.O. que precisam ter diferentes Bibliotecas e Dependências de uma forma mais "limpa" e isolada, isso é importante por questões de segurança, manutenção, configuração, parametrizações e etc, então:

"Eu não consigo enviar o -curl caso esteja no /bash do contêiner."

Não foi pensando para isso a sua Aplicação faz uma chamada externa consultando o https://endereço_IP:9292  e o valor retornado é tratado dentro da sua Aplicação

"Compartilhando um volume, ele gera o .json no meu local, mas exclui o arquivo .pdf"

O mesmo de cima

"Quando eu derrubo o contêiner, ele exclui automaticamente todos os .json gerados"

A  API não foi pensada para armazenar dados isso deve ser feito pela  Aplicação que você está usando, é como um websevice você Envia Dados( uma Consulta) e esse webservice Retorna algo e dentro da sua Aplicação vai ser decidido o que fazer com esse dado.

**Comment by patric-vinicios** [comment]
Show! Consegui implementar no projeto. Quando o arquivo é criado e deletado logo em seguida, ele vai para a pasta /tmp do Linux. Eu consegui pegar o arquivo rodando o comando `mv /tmp/boletos* ./` e tanto o PDF quanto a remessa foram gerados perfeitamente. 

Obrigado pela ajuda. 🖤

**Comment by rvalyi** [comment]
legal!

**Comment by mbcosta** [comment]
@patric-vinicios uma última questão, caso você acabe fazendo alguma alteração, correção ou melhoria tanto na API quanto na lib do BRCobranca por favor considere fazer um PR, é importante para ambos projetos a participação e colaboração de outros desenvolvedores.
